### ISSUE TITLE
Pretrained model not avaialble

### ISSUE THREAD

**Issue by joeyhng** [puffin444/optical_flow_prediction#1]
The downlaod link of the pretrained model (ladoga.graphics.cs.cmu.edu/jcwalker/final.caffemodel) does not work. Can you fix that? Thanks.

**Comment by puffin444** [comment]
Looks like that server is no longer accessible. Here is an alternative link:
https://www.dropbox.com/s/whj3g78fie9z5yh/final.caffemodel?dl=0

**Comment by joeyhng** [comment]
Thanks!

**Comment by lhw0772** [comment]
I tried to download an alternative link.
but I failed to download that while downloading 55% percent.
so please check the link again.
Thanks
