### ISSUE TITLE
Results obtained are not similar to paper

### ISSUE THREAD

**Issue by Arroosh** [puffin444/optical_flow_prediction#5]
Hello Jacob
I have run your code successfully on the server. When i run the file displayresult.m.
I got error

Index exceeds matrix dimensions.

Error in makeArrowFlowFigure (line 72)
    XData=get(children(2),'XData'); % retrieve the coordinates of the tips

I made a small change in makeArrowFlowFigure.m that is:
  XData=get(children(2),'XData'); to  XData=get(children,'XData');

Then the results has been displayed successfully.
I have downloaded images similar to paper but the results obtained are not similar to paper.
Can you help me in this regard where  i am going wrong?
![paper-fig1](https://user-images.githubusercontent.com/33623544/34551807-d2f99084-f13e-11e7-87da-8803fb3cba3d.png)
![paper-fig2](https://user-images.githubusercontent.com/33623544/34551808-d4b48b0e-f13e-11e7-868c-40a6b816d952.png)
![paper-fig3](https://user-images.githubusercontent.com/33623544/34551811-de31e35c-f13e-11e7-8e82-85155c9dd867.png)

**Comment by puffin444** [comment]
The provided model is trained on a different dataset (All groups other than 5) than the ones featured in the paper (traditional UCF101 splits). This leads to different testing results on some images.
